A data study on NYPD Motor vehicle Collisions

Dataset: https://data.cityofnewyork.us/Public-Safety/NYPD-Motor-Vehicle-Collisions-Crashes/h9gi-nx95

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [4]:
NYMVC = pd.read_csv("NYPD_Motor_Vehicle_Collisions_-_Crashes.csv")

In [6]:
NYMVC

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,09/13/2019,9:10,NaN,NaN,NaN,NaN,NaN,BROOKLYN BRIDGE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4204970,Sedan,Sedan,NaN,NaN,NaN
1,09/13/2019,8:00,NaN,NaN,40.642174,-74.020640,"(40.642174, -74.02064)",3 AVENUE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4205013,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
2,09/13/2019,18:45,NaN,NaN,40.682846,-73.953820,"(40.682846, -73.95382)",BEDFORD AVENUE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4206216,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
3,09/13/2019,15:52,NaN,NaN,40.762127,-73.997390,"(40.762127, -73.99739)",11 AVENUE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4206547,Sedan,Tow Truck / Wrecker,NaN,NaN,NaN
4,09/13/2019,11:10,NaN,NaN,40.694840,-73.983910,"(40.69484, -73.98391)",JOHNSON STREET,NaN,NaN,...,NaN,NaN,NaN,NaN,4205299,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
5,09/13/2019,11:20,QUEENS,11434.0,40.692250,-73.766690,"(40.69225, -73.76669)",LINDEN BOULEVARD,180 STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,4205223,Sedan,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN
6,09/13/2019,16:25,QUEENS,11366.0,40.729504,-73.780130,"(40.729504, -73.78013)",NaN,NaN,189-07 UNION TURNPIKE,...,Unspecified,NaN,NaN,NaN,4205179,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
7,09/13/2019,15:20,NaN,NaN,40.813374,-73.956276,"(40.813374, -73.956276)",AMSTERDAM AVENUE,NaN,NaN,...,NaN,NaN,NaN,NaN,4206397,Sedan,NaN,NaN,NaN,NaN
8,09/13/2019,0:02,BROOKLYN,11207.0,40.678160,-73.897484,"(40.67816, -73.897484)",PENNSYLVANIA AVENUE,JAMAICA AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4205156,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
9,09/13/2019,10:53,BROOKLYN,11229.0,40.613270,-73.946280,"(40.61327, -73.94628)",NaN,NaN,1551 EAST 28 STREET,...,NaN,NaN,NaN,NaN,4204980,Sedan,NaN,NaN,NaN,NaN
10,09/13/2019,14:00,NaN,NaN,40.770770,-73.917270,"(40.77077, -73.91727)",ASTORIA BOULEVARD,31 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4205662,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
11,09/13/2019,8:20,NaN,NaN,NaN,NaN,NaN,ASTORIA BOULEVARD,49 STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,4205660,Sedan,Box Truck,Bus,NaN,NaN
12,09/13/2019,7:40,BRONX,10472.0,40.826400,-73.875810,"(40.8264, -73.87581)",WATSON AVENUE,MANOR AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4205577,Bus,NaN,NaN,NaN,NaN
13,09/13/2019,21:30,BRONX,10455.0,40.818077,-73.914960,"(40.818077, -73.91496)",ELTON AVENUE,3 AVENUE,NaN,...,Backing Unsafely,NaN,NaN,NaN,4205314,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
14,09/13/2019,8:30,NaN,NaN,40.839783,-73.837030,"(40.839783, -73.83703)",EAST TREMONT AVENUE,ERICSON PLACE,NaN,...,Unspecified,NaN,NaN,NaN,4206310,Sedan,Box Truck,NaN,NaN,NaN
15,09/13/2019,6:00,BRONX,10466.0,40.889940,-73.854100,"(40.88994, -73.8541)",NaN,NaN,855 EAST 230 STREET,...,NaN,NaN,NaN,NaN,4204943,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
16,09/13/2019,7:15,NaN,NaN,40.877870,-73.870100,"(40.87787, -73.8701)",BRONX RIVER PARKWAY,NaN,NaN,...,Other Vehicular,NaN,NaN,NaN,4205198,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
17,09/13/2019,19:13,MANHATTAN,10065.0,40.768024,-73.970290,"(40.768024, -73.97029)",EAST 65 STREET,5 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4205839,Taxi,Taxi,NaN,NaN,NaN
18,09/13/2019,12:15,NaN,NaN,40.762410,-73.954430,"(40.76241, -73.95443)",FDR DRIVE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4205195,Taxi,Sedan,NaN,NaN,NaN
19,09/13/2019,6:20,NaN,NaN,40.771640,-73.871445,"(40.77164, -73.871445)",GRAND CENTRAL PKWY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4205402,Station Wagon/Sport Utility Vehicle,Pick-up Truck,NaN,NaN,NaN
20,09/13/2019,8:40,BROOKLYN,11211.0,40.714070,-73.954346,"(40.71407, -73.954346)",METROPOLITAN AVENUE,MARCY AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4205985,Van,Garbage or Refuse,NaN,NaN,NaN
21,09/13/2019,7:50,BRONX,10453.0,40.861862,-73.912820,"(40.861862, -73.91282)",WEST FORDHAM ROAD,MAJOR DEEGAN EXPRESSWAY,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4205047,Pick-up Truck,Taxi,NaN,NaN,NaN
22,09/13/2019,16:20,MANHATTAN,10032.0,40.837230,-73.938840,"(40.83723, -73.93884)",AMSTERDAM AVENUE,WEST 164 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4206121,Sedan,Motorcycle,NaN,NaN,NaN
23,09/13/2019,11:45,BROOKLYN,11223.0,40.598760,-73.977940,"(40.59876, -73.97794)",WEST 6 STREET,AVENUE T,NaN,...,Unspecified,Unspecified,Unspecified,NaN,4205209,Sedan,Sedan,Sedan,Sedan,NaN
24,09/13/2019,23:05,BROOKLYN,11207.0,40.675670,-73.897850,"(40.67567, -73.89785)",SHEFFIELD AVENUE,ATLANTIC AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4205797,Sedan,Bus,NaN,NaN,NaN
25,09/13/2019,18:30,QUEENS,11385.0,40.695496,-73.895880,"(40.695496, -73.89588)",60 STREET,79 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4205323,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
26,09/13/2019,9:30,MANHATTAN,10033.0,40.848682,-73.939224,"(40.848682, -73.939224)",WEST 178 STREET,FORT WASHINGTON AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4206119,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
27,09/13/2019,22:05,NaN,NaN,40.844864,-73.922560,"(40.844864, -73.92256)",CROSS BRONX EXPY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4205325,Station Wagon/Sport Utility Vehicle,Tractor Truck Diesel,NaN,NaN,NaN
28,09/13/2019,14:10,BROOKLYN,11232.0,40.654705,-74.007310,"(40.654705, -74.00731)",NaN,NaN,976 3 AVENUE,...,Unspecified,NaN,NaN,NaN,4205216,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
29,09/13/2019,13:45,BROOKLYN,11222.0,40.729523,-73.950980,"(40.729523, -73.95098)",NaN,NaN,211 MC GUINNESS BOULEVARD,...,Unspecified,NaN,NaN,NaN,4205081,Box Truck,Dump,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149047,01/01/2019,17:00,BROOKLYN,11206.0,40.701040,-73.954704,"(40.70104, -73.954704)",NaN,NaN,233 LEE AVENUE,...,Unspecified,NaN,NaN,NaN,4060548,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
149048,01/01/2019,12:00,BRONX,10465.0,40.836643,-73.821290,"(40.836643, -73.82129)",NaN,NaN,1155 VINCENT AVENUE,...,NaN,NaN,NaN,NaN,4060504,Sedan,NaN,NaN,NaN,NaN
149049,01/01/2019,12:17,NaN,NaN,40.734978,-73.861400,"(40.734978, -73.8614)",LONG ISLAND EXPRESSWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4060728,Station Wagon/Sport Utility Vehicle,Taxi,NaN,NaN,NaN
149050,01/01/2019,7:50,BROOKLYN,11236.0,40.633930,-73.893960,"(40.63393, -73.89396)",AVENUE N,EAST 94 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4060879,Sedan,Sedan,NaN,NaN,NaN
149051,01/01/2019,3:49,NaN,NaN,40.836480,-73.897736,"(40.83648, -73.897736)",CLAREMONT PARKWAY,NaN,NaN,...,NaN,NaN,NaN,NaN,4060607,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
149052,01/01/2019,11:00,QUEENS,11385.0,40.698704,-73.899740,"(40.698704, -73.89974)",NaN,NaN,1811 NORMAN STREET,...,NaN,NaN,NaN,NaN,4065827,Sedan,NaN,NaN,NaN,NaN
149053,01/01/2019,2:50,BROOKLYN,11234.0,40.618603,-73.932470,"(40.618603, -73.93247)",FLATBUSH AVENUE,AVENUE N,NaN,...,Unspecified,NaN,NaN,NaN,4060466,Station Wagon/Sport Utility Vehicle,Taxi,NaN,NaN,NaN
149054,01/01/2019,21:22,BRONX,10467.0,40.884014,-73.879100,"(40.884014, -73.8791)",DEKALB AVENUE,EAST 212 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4060870,Sedan,NaN,NaN,NaN,NaN
149055,01/01/2019,1:05,BROOKLYN,11207.0,40.674397,-73.896515,"(40.674397, -73.896515)",PENNSYLVANIA AVENUE,LIBERTY AVENUE,NaN,...,NaN,NaN,NaN,NaN,4060742,Sedan,NaN,NaN,NaN,NaN
149056,01/01/2019,9:00,STATEN ISLAND,10310.0,40.626190,-74.119680,"(40.62619, -74.11968)",CLOVE LAKE PLACE,CLOVE ROAD,NaN,...,Unspecified,NaN,NaN,NaN,4062126,Pick-up Truck,NaN,NaN,NaN,NaN
149057,01/01/2019,4:30,BROOKLYN,11236.0,40.630157,-73.897300,"(40.630157, -73.8973)",NaN,NaN,1449 EAST 88 STREET,...,NaN,NaN,NaN,NaN,4063063,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
149058,01/01/2019,15:50,NaN,NaN,NaN,NaN,NaN,3 AVENUE,EAST 161 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4060609,Sedan,Sedan,NaN,NaN,NaN
149059,01/01/2019,14:10,NaN,NaN,40.740940,-74.007484,"(40.74094, -74.007484)",WEST 13 STREET,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4060825,Station Wagon/Sport Utility Vehicle,Taxi,NaN,NaN,NaN
149060,01/01/2019,0:00,NaN,NaN,40.680540,-73.886740,"(40.68054, -73.88674)",ARLINGTON AVENUE,NaN,NaN,...,Unspecified,Unspecified,NaN,NaN,4060899,Station Wagon/Sport Utility Vehicle,Sedan,Sedan,NaN,NaN
149061,01/01/2019,2:04,NaN,NaN,40.762676,-73.954346,"(40.762676, -73.954346)",FDR DRIVE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4060622,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
149062,01/01/2019,1:30,NaN,NaN,NaN,NaN,NaN,NARROWS ROAD NORTH,BRITTON STREET,NaN,...,NaN,NaN,NaN,NaN,4129434,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
149063,01/01/2019,12:58,BRONX,10455.0,40.814934,-73.914960,"(40.814934, -73.91496)",EAST 149 STREET,BROOK AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4060505,Pick-up Truck,Sedan,NaN,NaN,NaN
149064,01/01/2019,1:46,STATEN ISLAND,10307.0,40.503387,-74.248830,"(40.503387, -74.24883)",HYLAN BOULEVARD,FINLAY STREET,NaN,...,Unspecified,NaN,NaN,NaN,4060464,Pick-up Truck,Motorcycle,NaN,NaN,NaN
149065,01/01/2019,17:47,NaN,NaN,40.780060,-73.988174,"(40.78006, -73.988174)",HENRY HUDSON PARKWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4060600,Sedan,Sedan,NaN,NaN,NaN
149066,01/01/2019,12:40,BROOKLYN,11232.0,40.655430,-74.003265,"(40.65543, -74.003265)",4 AVENUE,34 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4060827,Sedan,Sedan,NaN,NaN,NaN
149067,01/01/2019,6:30,MANHATTAN,10029.0,40.794280,-73.949020,"(40.79428, -73.94902)",MADISON AVENUE,EAST 107 STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,4060501,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN
149068,01/01/2019,4:35,MANHATTAN,10012.0,40.725430,-73.996780,"(40.72543, -73.99678)",BROADWAY,EAST HOUSTON STREET,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4060674,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
149069,01/01/2019,1:18,NaN,NaN,40.659016,-73.854730,"(40.659016, -73.85473)",BELT PARKWAY,NaN,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4060418,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
149070,01/01/2019,2:00,STATEN ISLAND,10304.0,40.618813,-74.082290,"(40.618813, -74.08229)",NaN,NaN,107 OSGOOD AVENUE,...,NaN,NaN,NaN,NaN,4061596,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
149071,01/01/2019,7:03,NaN,NaN,40.868458,-73.821400,"(40.868458, -73.8214)",HUTCHINSON RIVER PARKWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4060550,Taxi,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
149072,01/01/2019,4:12,MANHATTAN,10001.0,40.749590,-74.002790,"(40.74959, -74.00279)",WEST 26 STREET,10 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4061312,Sedan,Taxi,NaN,NaN,NaN
149073,01/01/2019,18:45,NaN,NaN,40.678596,-73.882416,"(40.678596, -73.882416)",ATLANTIC AVENUE,ESSEX STREET,NaN,...,Unspecified,NaN,NaN,NaN,4060753,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
149074,01/01/2019,10:55,QUEENS,11354.0,40.769093,-73.825800,"(40.769093, -73.8258)",143 STREET,32 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4060567,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
149075,01/01/2019,8:37,QUEENS,11373.0,40.730880,-73.871635,"(40.73088, -73.871635)",WOODHAVEN BOULEVARD,60 ROAD,NaN,...,NaN,NaN,NaN,NaN,4060463,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
149076,01/01/2019,20:55,QUEENS,11435.0,40.712112,-73.812460,"(40.712112, -73.81246)",84 DRIVE,SMEDLEY STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,4060580,Station Wagon/Sport Utility Vehicle,Sedan,Sedan,NaN,NaN

In [9]:
NYMVC["DATE"] = pd.to_datetime(NYMVC["DATE"])
NYMVC.dtypes

DATE                             datetime64[ns]
TIME                                     object
BOROUGH                                  object
ZIP CODE                                float64
LATITUDE                                float64
LONGITUDE                               float64
LOCATION                                 object
ON STREET NAME                           object
CROSS STREET NAME                        object
OFF STREET NAME                          object
NUMBER OF PERSONS INJURED                 int64
NUMBER OF PERSONS KILLED                  int64
NUMBER OF PEDESTRIANS INJURED             int64
NUMBER OF PEDESTRIANS KILLED              int64
NUMBER OF CYCLIST INJURED                 int64
NUMBER OF CYCLIST KILLED                  int64
NUMBER OF MOTORIST INJURED                int64
NUMBER OF MOTORIST KILLED                 int64
CONTRIBUTING FACTOR VEHICLE 1            object
CONTRIBUTING FACTOR VEHICLE 2            object
CONTRIBUTING FACTOR VEHICLE 3            object
CONTRIBUTING FACTOR VEHICLE 4            object
CONTRIBUTING FACTOR VEHICLE 5            object
COLLISION_ID                              int64
VEHICLE TYPE CODE 1                      object
VEHICLE TYPE CODE 2                      object
VEHICLE TYPE CODE 3                      object
VEHICLE TYPE CODE 4                      object
VEHICLE TYPE CODE 5                      object
dtype: object

In [11]:
NYMVC

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,2019-09-13,9:10,NaN,NaN,NaN,NaN,NaN,BROOKLYN BRIDGE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4204970,Sedan,Sedan,NaN,NaN,NaN
1,2019-09-13,8:00,NaN,NaN,40.642174,-74.020640,"(40.642174, -74.02064)",3 AVENUE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4205013,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
2,2019-09-13,18:45,NaN,NaN,40.682846,-73.953820,"(40.682846, -73.95382)",BEDFORD AVENUE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4206216,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
3,2019-09-13,15:52,NaN,NaN,40.762127,-73.997390,"(40.762127, -73.99739)",11 AVENUE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4206547,Sedan,Tow Truck / Wrecker,NaN,NaN,NaN
4,2019-09-13,11:10,NaN,NaN,40.694840,-73.983910,"(40.69484, -73.98391)",JOHNSON STREET,NaN,NaN,...,NaN,NaN,NaN,NaN,4205299,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
5,2019-09-13,11:20,QUEENS,11434.0,40.692250,-73.766690,"(40.69225, -73.76669)",LINDEN BOULEVARD,180 STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,4205223,Sedan,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN
6,2019-09-13,16:25,QUEENS,11366.0,40.729504,-73.780130,"(40.729504, -73.78013)",NaN,NaN,189-07 UNION TURNPIKE,...,Unspecified,NaN,NaN,NaN,4205179,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
7,2019-09-13,15:20,NaN,NaN,40.813374,-73.956276,"(40.813374, -73.956276)",AMSTERDAM AVENUE,NaN,NaN,...,NaN,NaN,NaN,NaN,4206397,Sedan,NaN,NaN,NaN,NaN
8,2019-09-13,0:02,BROOKLYN,11207.0,40.678160,-73.897484,"(40.67816, -73.897484)",PENNSYLVANIA AVENUE,JAMAICA AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4205156,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
9,2019-09-13,10:53,BROOKLYN,11229.0,40.613270,-73.946280,"(40.61327, -73.94628)",NaN,NaN,1551 EAST 28 STREET,...,NaN,NaN,NaN,NaN,4204980,Sedan,NaN,NaN,NaN,NaN
10,2019-09-13,14:00,NaN,NaN,40.770770,-73.917270,"(40.77077, -73.91727)",ASTORIA BOULEVARD,31 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4205662,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
11,2019-09-13,8:20,NaN,NaN,NaN,NaN,NaN,ASTORIA BOULEVARD,49 STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,4205660,Sedan,Box Truck,Bus,NaN,NaN
12,2019-09-13,7:40,BRONX,10472.0,40.826400,-73.875810,"(40.8264, -73.87581)",WATSON AVENUE,MANOR AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4205577,Bus,NaN,NaN,NaN,NaN
13,2019-09-13,21:30,BRONX,10455.0,40.818077,-73.914960,"(40.818077, -73.91496)",ELTON AVENUE,3 AVENUE,NaN,...,Backing Unsafely,NaN,NaN,NaN,4205314,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
14,2019-09-13,8:30,NaN,NaN,40.839783,-73.837030,"(40.839783, -73.83703)",EAST TREMONT AVENUE,ERICSON PLACE,NaN,...,Unspecified,NaN,NaN,NaN,4206310,Sedan,Box Truck,NaN,NaN,NaN
15,2019-09-13,6:00,BRONX,10466.0,40.889940,-73.854100,"(40.88994, -73.8541)",NaN,NaN,855 EAST 230 STREET,...,NaN,NaN,NaN,NaN,4204943,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
16,2019-09-13,7:15,NaN,NaN,40.877870,-73.870100,"(40.87787, -73.8701)",BRONX RIVER PARKWAY,NaN,NaN,...,Other Vehicular,NaN,NaN,NaN,4205198,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
17,2019-09-13,19:13,MANHATTAN,10065.0,40.768024,-73.970290,"(40.768024, -73.97029)",EAST 65 STREET,5 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4205839,Taxi,Taxi,NaN,NaN,NaN
18,2019-09-13,12:15,NaN,NaN,40.762410,-73.954430,"(40.76241, -73.95443)",FDR DRIVE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4205195,Taxi,Sedan,NaN,NaN,NaN
19,2019-09-13,6:20,NaN,NaN,40.771640,-73.871445,"(40.77164, -73.871445)",GRAND CENTRAL PKWY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4205402,Station Wagon/Sport Utility Vehicle,Pick-up Truck,NaN,NaN,NaN
20,2019-09-13,8:40,BROOKLYN,11211.0,40.714070,-73.954346,"(40.71407, -73.954346)",METROPOLITAN AVENUE,MARCY AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4205985,Van,Garbage or Refuse,NaN,NaN,NaN
21,2019-09-13,7:50,BRONX,10453.0,40.861862,-73.912820,"(40.861862, -73.91282)",WEST FORDHAM ROAD,MAJOR DEEGAN EXPRESSWAY,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4205047,Pick-up Truck,Taxi,NaN,NaN,NaN
22,2019-09-13,16:20,MANHATTAN,10032.0,40.837230,-73.938840,"(40.83723, -73.93884)",AMSTERDAM AVENUE,WEST 164 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4206121,Sedan,Motorcycle,NaN,NaN,NaN
23,2019-09-13,11:45,BROOKLYN,11223.0,40.598760,-73.977940,"(40.59876, -73.97794)",WEST 6 STREET,AVENUE T,NaN,...,Unspecified,Unspecified,Unspecified,NaN,4205209,Sedan,Sedan,Sedan,Sedan,NaN
24,2019-09-13,23:05,BROOKLYN,11207.0,40.675670,-73.897850,"(40.67567, -73.89785)",SHEFFIELD AVENUE,ATLANTIC AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4205797,Sedan,Bus,NaN,NaN,NaN
25,2019-09-13,18:30,QUEENS,11385.0,40.695496,-73.895880,"(40.695496, -73.89588)",60 STREET,79 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4205323,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
26,2019-09-13,9:30,MANHATTAN,10033.0,40.848682,-73.939224,"(40.848682, -73.939224)",WEST 178 STREET,FORT WASHINGTON AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4206119,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
27,2019-09-13,22:05,NaN,NaN,40.844864,-73.922560,"(40.844864, -73.92256)",CROSS BRONX EXPY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4205325,Station Wagon/Sport Utility Vehicle,Tractor Truck Diesel,NaN,NaN,NaN
28,2019-09-13,14:10,BROOKLYN,11232.0,40.654705,-74.007310,"(40.654705, -74.00731)",NaN,NaN,976 3 AVENUE,...,Unspecified,NaN,NaN,NaN,4205216,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
29,2019-09-13,13:45,BROOKLYN,11222.0,40.729523,-73.950980,"(40.729523, -73.95098)",NaN,NaN,211 MC GUINNESS BOULEVARD,...,Unspecified,NaN,NaN,NaN,4205081,Box Truck,Dump,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149047,2019-01-01,17:00,BROOKLYN,11206.0,40.701040,-73.954704,"(40.70104, -73.954704)",NaN,NaN,233 LEE AVENUE,...,Unspecified,NaN,NaN,NaN,4060548,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
149048,2019-01-01,12:00,BRONX,10465.0,40.836643,-73.821290,"(40.836643, -73.82129)",NaN,NaN,1155 VINCENT AVENUE,...,NaN,NaN,NaN,NaN,4060504,Sedan,NaN,NaN,NaN,NaN
149049,2019-01-01,12:17,NaN,NaN,40.734978,-73.861400,"(40.734978, -73.8614)",LONG ISLAND EXPRESSWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4060728,Station Wagon/Sport Utility Vehicle,Taxi,NaN,NaN,NaN
149050,2019-01-01,7:50,BROOKLYN,11236.0,40.633930,-73.893960,"(40.63393, -73.89396)",AVENUE N,EAST 94 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4060879,Sedan,Sedan,NaN,NaN,NaN
149051,2019-01-01,3:49,NaN,NaN,40.836480,-73.897736,"(40.83648, -73.897736)",CLAREMONT PARKWAY,NaN,NaN,...,NaN,NaN,NaN,NaN,4060607,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
149052,2019-01-01,11:00,QUEENS,11385.0,40.698704,-73.899740,"(40.698704, -73.89974)",NaN,NaN,1811 NORMAN STREET,...,NaN,NaN,NaN,NaN,4065827,Sedan,NaN,NaN,NaN,NaN
149053,2019-01-01,2:50,BROOKLYN,11234.0,40.618603,-73.932470,"(40.618603, -73.93247)",FLATBUSH AVENUE,AVENUE N,NaN,...,Unspecified,NaN,NaN,NaN,4060466,Station Wagon/Sport Utility Vehicle,Taxi,NaN,NaN,NaN
149054,2019-01-01,21:22,BRONX,10467.0,40.884014,-73.879100,"(40.884014, -73.8791)",DEKALB AVENUE,EAST 212 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4060870,Sedan,NaN,NaN,NaN,NaN
149055,2019-01-01,1:05,BROOKLYN,11207.0,40.674397,-73.896515,"(40.674397, -73.896515)",PENNSYLVANIA AVENUE,LIBERTY AVENUE,NaN,...,NaN,NaN,NaN,NaN,4060742,Sedan,NaN,NaN,NaN,NaN
149056,2019-01-01,9:00,STATEN ISLAND,10310.0,40.626190,-74.119680,"(40.62619, -74.11968)",CLOVE LAKE PLACE,CLOVE ROAD,NaN,...,Unspecified,NaN,NaN,NaN,4062126,Pick-up Truck,NaN,NaN,NaN,NaN
149057,2019-01-01,4:30,BROOKLYN,11236.0,40.630157,-73.897300,"(40.630157, -73.8973)",NaN,NaN,1449 EAST 88 STREET,...,NaN,NaN,NaN,NaN,4063063,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
149058,2019-01-01,15:50,NaN,NaN,NaN,NaN,NaN,3 AVENUE,EAST 161 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4060609,Sedan,Sedan,NaN,NaN,NaN
149059,2019-01-01,14:10,NaN,NaN,40.740940,-74.007484,"(40.74094, -74.007484)",WEST 13 STREET,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4060825,Station Wagon/Sport Utility Vehicle,Taxi,NaN,NaN,NaN
149060,2019-01-01,0:00,NaN,NaN,40.680540,-73.886740,"(40.68054, -73.88674)",ARLINGTON AVENUE,NaN,NaN,...,Unspecified,Unspecified,NaN,NaN,4060899,Station Wagon/Sport Utility Vehicle,Sedan,Sedan,NaN,NaN
149061,2019-01-01,2:04,NaN,NaN,40.762676,-73.954346,"(40.762676, -73.954346)",FDR DRIVE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4060622,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
149062,2019-01-01,1:30,NaN,NaN,NaN,NaN,NaN,NARROWS ROAD NORTH,BRITTON STREET,NaN,...,NaN,NaN,NaN,NaN,4129434,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
149063,2019-01-01,12:58,BRONX,10455.0,40.814934,-73.914960,"(40.814934, -73.91496)",EAST 149 STREET,BROOK AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4060505,Pick-up Truck,Sedan,NaN,NaN,NaN
149064,2019-01-01,1:46,STATEN ISLAND,10307.0,40.503387,-74.248830,"(40.503387, -74.24883)",HYLAN BOULEVARD,FINLAY STREET,NaN,...,Unspecified,NaN,NaN,NaN,4060464,Pick-up Truck,Motorcycle,NaN,NaN,NaN
149065,2019-01-01,17:47,NaN,NaN,40.780060,-73.988174,"(40.78006, -73.988174)",HENRY HUDSON PARKWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4060600,Sedan,Sedan,NaN,NaN,NaN
149066,2019-01-01,12:40,BROOKLYN,11232.0,40.655430,-74.003265,"(40.65543, -74.003265)",4 AVENUE,34 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4060827,Sedan,Sedan,NaN,NaN,NaN
149067,2019-01-01,6:30,MANHATTAN,10029.0,40.794280,-73.949020,"(40.79428, -73.94902)",MADISON AVENUE,EAST 107 STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,4060501,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN
149068,2019-01-01,4:35,MANHATTAN,10012.0,40.725430,-73.996780,"(40.72543, -73.99678)",BROADWAY,EAST HOUSTON STREET,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4060674,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
149069,2019-01-01,1:18,NaN,NaN,40.659016,-73.854730,"(40.659016, -73.85473)",BELT PARKWAY,NaN,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4060418,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
149070,2019-01-01,2:00,STATEN ISLAND,10304.0,40.618813,-74.082290,"(40.618813, -74.08229)",NaN,NaN,107 OSGOOD AVENUE,...,NaN,NaN,NaN,NaN,4061596,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
149071,2019-01-01,7:03,NaN,NaN,40.868458,-73.821400,"(40.868458, -73.8214)",HUTCHINSON RIVER PARKWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4060550,Taxi,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
149072,2019-01-01,4:12,MANHATTAN,10001.0,40.749590,-74.002790,"(40.74959, -74.00279)",WEST 26 STREET,10 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4061312,Sedan,Taxi,NaN,NaN,NaN
149073,2019-01-01,18:45,NaN,NaN,40.678596,-73.882416,"(40.678596, -73.882416)",ATLANTIC AVENUE,ESSEX STREET,NaN,...,Unspecified,NaN,NaN,NaN,4060753,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
149074,2019-01-01,10:55,QUEENS,11354.0,40.769093,-73.825800,"(40.769093, -73.8258)",143 STREET,32 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4060567,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
149075,2019-01-01,8:37,QUEENS,11373.0,40.730880,-73.871635,"(40.73088, -73.871635)",WOODHAVEN BOULEVARD,60 ROAD,NaN,...,NaN,NaN,NaN,NaN,4060463,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
149076,2019-01-01,20:55,QUEENS,11435.0,40.712112,-73.812460,"(40.712112, -73.81246)",84 DRIVE,SMEDLEY STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,4060580,Station Wagon/Sport Utility Vehicle,Sedan,Sedan,NaN,NaN

Let's create a dataframe that represents the collisions that happened in only the month of January.